id: PA679E4AC
initial_creation_type: input
source_metadata:
  title: Jambhala Series
  language: en
  description: 'Texts related to Jambhala (dzam bha la; rmugs ’dzin), the deity of
    wealth, in all his various forms:'
  volume:
    b2e2efd759794ec9828abecc5b2dadde:
      title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth
        Deity White Jambhala'
      parent: Sādhanas
    673457702f4249c7b76a290905f25810:
      title: A Sādhana of Jambhala
      parent: Sādhanas
    8bd79f5249e743afa89c8860346f50f5:
      title: Sang Offering to Yellow Jambhala
      parent: Sang Offering
created_at: '2022-03-01T04:00:04.800485'
last_modified_at: '2022-03-01T04:00:04.800491'
